### ISSUE TITLE
All members contribute to the concept + ran it successfully on their system(s)

### ISSUE THREAD

**Issue by AyserJamshidi** [cis3296s22/patreon-discord-announcer#11]

**Comment by AyserJamshidi** [comment]
I've committed.

**Comment by apsawicki** [comment]
was able to build and run, had slight warnings during runtime but it was still able to produce the expected result

**Comment by apsawicki** [comment]
was able to commit/push to github

**Comment by 3cbb** [comment]
Was able to build, run, and commit to github

**Comment by AyserJamshidi** [comment]
All members were able to build, run and contribute to the project.  Closing.
