### ISSUE TITLE
'java' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by free-mana** [cis3296s22/patreon-discord-announcer#26]
I keep getting an error message when I try to run the JAR as per the instructions. I have JDK 17 installed, and I'm on Windows 10.

Edition	Windows 10 Pro
Version	21H1
Installed on	‎6/‎2/‎2021
OS build	19043.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by AyserJamshidi** [comment]
Please elaborate on what the error message is, or provide a picture please.  Team members have compiled and ran with JDK 8, 9, 11, 17 and 18.

**Comment by free-mana** [comment]
![image](https://user-images.githubusercontent.com/58083363/159566395-cd872827-defe-4567-95d2-b3d4248d246e.png)

**Comment by AyserJamshidi** [comment]
As per the instructions, you must have Java installed.  Since "java" is not a recognized command, you have either improperly installed Java or do not have a system-wide or user-wide installation of Java.

**Comment by free-mana** [comment]
That's what I thought might be the problem at first, so I manually installed jdk 17 and tried again, but it still didn't work. I just did it again just now, and it says that it was successful, but the command still doesn't work.
![image](https://user-images.githubusercontent.com/58083363/159566906-12fcdbdf-0066-440f-9765-46579c6ea5ae.png)

**Comment by free-mana** [comment]
Figured it out-- apparently the command line had to be restarted after installing java in order for it to be recognized.
