### ISSUE TITLE
It only fully runs half of the time

### ISSUE THREAD

**Issue by DarlinKola1** [cis3296s22/patreon-discord-announcer#32]
![Code](https://user-images.githubusercontent.com/89646919/159696729-5c29b5ba-70c4-4d8d-bbcf-97e5652165a0.PNG)

Some of the times that I ran it through the command line it says finding all the posts on the front page but then just brings me back to the command line.

**Comment by apsawicki** [comment]
Problem has been solved, the latest release should be consistent. Please test and if any issues occur then make a new issue/ticket
