### ISSUE TITLE
Instructions for after bot check 

### ISSUE THREAD

**Issue by stevetolvaj** [cis3296s22/patreon-discord-announcer#33]
The instructions were mostly clear. The only issue I ran into was that I tried to create an account for Patreon instead of returning to the terminal to continue after bot check. Maybe add After doing so and reaching the Patreon login screen, follow the instructions in the terminal. Otherwise, no other issues were found.

**Comment by apsawicki** [comment]
the program now will hide the GUI of the driver for you so you won't see the patreon page
