### ISSUE TITLE
I do not know where the config.json file is

### ISSUE THREAD

**Issue by SkylerShaw** [cis3296s22/patreon-discord-announcer#40]
You mention a config.json file in your instructions to run it, but I do not see this file.

**Comment by csaputro** [comment]
The config.json file is inside the root directory
![image](https://user-images.githubusercontent.com/89764190/160671248-2bf8964e-193e-41df-8981-f72e41074959.png)

**Comment by Jsmalriat** [comment]
Resolved, latest release contains config.json.
