### ISSUE TITLE
Build from Source - mvn command issue 

### ISSUE THREAD

**Issue by ccho-0508** [cis3296s22/patreon-discord-announcer#63]
couldn't run the mvn command

**Comment by AyserJamshidi** [comment]
Does your system have Maven installed?  If so, please show output.  If not, that is one of the build requirements.

**Comment by ccho-0508** [comment]
I don't think it says in the readme it's a requirement? + there are no instructions?

**Comment by Jsmalriat** [comment]
README has been updated to show the missing instructions and requirements.
