### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by HaydenDowns** [cis3296s22/patreon-discord-announcer#83]
The instructions in the Readme are a little tough to follow. As all of us being computer science majors it is not too bad to follow but for anyone else I could see them having a lot more trouble. The steps for downloading and adding the bot seem to go back and forth between multiple sequences and I found myself not knowing where I was in the instructions. So making them a little more clear or making the process easier would be helpful.

**Comment by Jsmalriat** [comment]
Created an easier route for those not familiar with more technical side of our application and Discord bots.
